### ISSUE TITLE
更新异常

### ISSUE THREAD

**Issue by nmww** [yanue/V2rayU#1106]
提交 Issue 之前请先在issue上搜索是否有相似问题, 看看能不能解决问题 (有太多相同的issue,没精力处理)。
除非特殊情况，请完整填写以下所有问题，不按模板发的 issue 将直接被关闭。

1) 你正在使用的 V2RayU 和 Mac 版本 ？

2) 你遇到的问题是什么？（请描述具体现象，比如访问超时，TLS 证书错误等）
更新异常
3) 请附上你的配置（提交 Issue 前请隐藏服务器端IP地址）。

```javascript
    // 在这里附上配置信息
```
4)  请附上出错时软件输出的错误日志。

```javascript
    // 在这里附上日志信息
```
<img width="258" alt="image" src="https://user-images.githubusercontent.com/6917516/189249260-4f178a0b-4f94-42c2-af33-7f660e35d3ba.png">

请预览一下你填的内容再提交。

**Comment by wchyan** [comment]
os: monterey 12.5
Model: Mac14,7, BootROM 7459.141.1, proc 8:4:4 processors, 16 GB, SMC 
Graphics: Apple M2, Apple M2, Built-In


-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               V2rayU [974]
Path:                  /Applications/V2rayU.app/Contents/MacOS/V2rayU
Identifier:            net.yanue.V2rayU
Version:               3.3.0 (3.3.0)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-09-11 09:50:44.7290 +0800
OS Version:            macOS 12.5 (21G72)
Report Version:        12
Anonymous UUID:      


Time Awake Since Boot: 100 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called


Application Specific Backtrace 0:
0   CoreFoundation                      0x000000019af7d1a8 __exceptionPreprocess + 240
1   libobjc.A.dylib                     0x000000019acc7e04 objc_exception_throw + 60
2   Foundation                          0x000000019be63130 -[NSConcreteTask dealloc] + 0
3   V2rayU                              0x0000000104a6ec38 V2rayU + 76856
4   V2rayU                              0x0000000104a65e94 V2rayU + 40596
5   V2rayU                              0x0000000104a668ac V2rayU + 43180
6   CoreFoundation                      0x000000019aef0864 -[NSSet makeObjectsPerformSelector:] + 216
7   AppKit                              0x000000019da3f51c -[NSIBObjectData nibInstantiateWithOwner:options:topLevelObjects:] + 1080
8   AppKit                              0x000000019da33800 loadNib + 416
9   AppKit                              0x000000019da32d30 +[NSBundle(NSNibLoading) _loadNibFile:nameTable:options:withZone:ownerBundle:] + 800
10  AppKit                              0x000000019da32934 -[NSBundle(NSNibLoading) loadNibNamed:owner:topLevelObjects:] + 220
11  AppKit                              0x000000019da32704 +[NSBundle(NSNibLoading) loadNibNamed:owner:] + 388
12  AppKit                              0x000000019da244d0 NSApplicationMain + 576
13  V2rayU                              0x0000000104a621e4 V2rayU + 25060
14  dyld                                0x0000000104d5908c start + 520


Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x19adfad98 __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x19ae2fee0 pthread_kill + 288
2   libsystem_c.dylib             	       0x19ad6a340 abort + 168
3   libc++abi.dylib               	       0x19adeab08 abort_message + 132
4   libc++abi.dylib               	       0x19adda950 demangling_terminate_handler() + 336
5   libobjc.A.dylib               	       0x19acd0320 _objc_terminate() + 144
6   libc++abi.dylib               	       0x19ade9ea4 std::__terminate(void (*)()) + 20
7   libc++abi.dylib               	       0x19adecc1c __cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*) + 36
8   libc++abi.dylib               	       0x19adecbc8 __cxa_throw + 140
9   libobjc.A.dylib               	       0x19acc7f6c objc_exception_throw + 420
10  Foundation                    	       0x19be63130 -[NSConcreteTask terminationStatus] + 204
11  V2rayU                        	       0x104a6ec38 0x104a5c000 + 76856
12  V2rayU                        	       0x104a65e94 0x104a5c000 + 40596
13  V2rayU                        	       0x104a668ac 0x104a5c000 + 43180
14  CoreFoundation                	       0x19aef0864 -[NSSet makeObjectsPerformSelector:] + 216
15  AppKit                        	       0x19da3f51c -[NSIBObjectData nibInstantiateWithOwner:options:topLevelObjects:] + 1080
16  AppKit                        	       0x19da33800 loadNib + 416
17  AppKit                        	       0x19da32d30 +[NSBundle(NSNibLoading) _loadNibFile:nameTable:options:withZone:ownerBundle:] + 800
18  AppKit                        	       0x19da32934 -[NSBundle(NSNibLoading) loadNibNamed:owner:topLevelObjects:] + 220
19  AppKit                        	       0x19da32704 +[NSBundle(NSNibLoading) loadNibNamed:owner:] + 388
20  AppKit                        	       0x19da244d0 NSApplicationMain + 576
21  V2rayU                        	       0x104a621e4 0x104a5c000 + 25060
22  dyld                          	       0x104d5908c start + 520

Thread 1:
0   libsystem_pthread.dylib       	       0x19ae2b078 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	       0x19ae2b078 start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	       0x19ae2b078 start_wqthread + 0


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x000000019adee0f5   x5: 0x000000016b3a18c0   x6: 0x000000000000006e   x7: 0x0000000000000001
    x8: 0x97010e23058c3a4c   x9: 0x97010e220150ffcc  x10: 0x0000000000000200  x11: 0x000000000000000b
   x12: 0x000000000000000b  x13: 0x000000019b33e2ed  x14: 0x000000019adee11b  x15: 0x0000000000934bcb
   x16: 0x0000000000000148  x17: 0x00000001f4f4f680  x18: 0x0000000000000000  x19: 0x0000000000000006
   x20: 0x0000000104dcc580  x21: 0x0000000000000103  x22: 0x0000000104dcc660  x23: 0x000000014961fc20
   x24: 0x000000015970a4c0  x25: 0x000070756b636162  x26: 0x000000015961e7f0  x27: 0x0000000159716af0
   x28: 0x00000001f3db2c38   fp: 0x000000016b3a1830   lr: 0x000000019ae2fee0
    sp: 0x000000016b3a1810   pc: 0x000000019adfad98 cpsr: 0x40001000
   far: 0x000000016f333df8  esr: 0x56000080  Address size fault

Binary Images:
       0x19adf1000 -        0x19ae28fff libsystem_kernel.dylib (*) <67f22904-88ed-3847-bbf0-5c4c599fd79e> /usr/lib/system/libsystem_kernel.dylib
       0x19ae29000 -        0x19ae35fff libsystem_pthread.dylib (*) <f32ff902-ba43-30b0-ad43-a2a8a9ff69fe> /usr/lib/system/libsystem_pthread.dylib
       0x19acf0000 -        0x19ad71fff libsystem_c.dylib (*) <93fc2587-038e-31e1-b16b-369979e72cb1> /usr/lib/system/libsystem_c.dylib
       0x19add9000 -        0x19adf0fff libc++abi.dylib (*) <a260a581-f4a9-3036-bb4f-16a9c6cc54d5> /usr/lib/libc++abi.dylib
       0x19acaf000 -        0x19acecfff libobjc.A.dylib (*) <3d936842-5903-31ad-b1ae-1de4f4b448a6> /usr/lib/libobjc.A.dylib
       0x19bd7c000 -        0x19c16dfff com.apple.Foundation (6.9) <59ff845a-05b2-3b64-ae06-6ef1d6aee83e> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
       0x104a5c000 -        0x104b3bfff net.yanue.V2rayU (3.3.0) <73ec5a51-3e6f-396f-94dd-b0eb68a027c0> /Applications/V2rayU.app/Contents/MacOS/V2rayU
       0x19ae78000 -        0x19b3befff com.apple.CoreFoundation (6.9) <1643f3d9-7049-37e4-b844-c0c0a42bde3b> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
       0x19da21000 -        0x19e8d9fff com.apple.AppKit (6.9) <07bc3607-552a-3eb9-a941-4911c589dbc5> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x104d54000 -        0x104db3fff dyld (*) <75627683-a780-32ad-ae34-cf86dd23a26b> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)
Writable regions: Total=498.5M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=498.5M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                   256K        1 
ColorSync                          528K       23 
CoreGraphics                        16K        1 
CoreServices                       208K        1 
Dispatch continuations            64.0M        1 
Foundation                          16K        1 
Kernel Alloc Once                   32K        1 
MALLOC                            64.3M       26 
MALLOC guard page                  192K        9 
MALLOC_MEDIUM (reserved)         360.0M        3         reserved VM address space (unallocated)
STACK GUARD                       56.1M        4 
Stack                             9808K        4 
VM_ALLOCATE                         48K        3 
__AUTH                            2244K      228 
__AUTH_CONST                      17.5M      407 
__CTF                               756        1 
__DATA                            11.2M      404 
__DATA_CONST                      15.3M      419 
__DATA_DIRTY                      1440K      162 
__FONT_DATA                          4K        1 
__LINKEDIT                       579.7M       11 
__OBJC_CONST                      2589K      198 
__OBJC_RO                         83.0M        1 
__OBJC_RW                         3168K        1 
__TEXT                           426.4M      436 
__UNICODE                          592K        1 
dyld private memory               1024K        1 
mapped file                      135.4M       16 
shared memory                      848K       13 
===========                     =======  ======= 
TOTAL                              1.8G     2378 
TOTAL, minus reserved VM space     1.4G     2378 



-----------
Full Report
-----------

{"app_name":"V2rayU","timestamp":"2022-09-11 09:50:46.00 +0800","app_version":"3.3.0","slice_uuid":"73ec5a51-3e6f-396f-94dd-b0eb68a027c0","build_version":"3.3.0","platform":1,"bundleID":"net.yanue.V2rayU","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.5 (21G72)","incident_id":"CA82F05D-F7DB-41D4-9985-B6CABAF7409A","name":"V2rayU"}
{
  "uptime" : 100,
  "procLaunch" : "2022-09-11 09:50:42.7500 +0800",
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "Mac14,7",
  "procStartAbsTime" : 2544599242,
  "coalitionID" : 999,
  "osVersion" : {
    "train" : "macOS 12.5",
    "build" : "21G72",
    "releaseType" : "User"
  },
  "captureTime" : "2022-09-11 09:50:44.7290 +0800",
  "incident" : "",
  "bug_type" : "309",
  "pid" : 974,
  "procExitAbsTime" : 2591968355,
  "translated" : false,
  "cpuType" : "ARM-64",
  "procName" : "V2rayU",
  "procPath" : "\/Applications\/V2rayU.app\/Contents\/MacOS\/V2rayU",
  "bundleInfo" : {"CFBundleShortVersionString":"3.3.0","CFBundleVersion":"3.3.0","CFBundleIdentifier":"net.yanue.V2rayU"},
  "storeInfo" : {"deviceIdentifierForVendor":"1B7D01EA-B2A1-5AAB-BE04-09325CD73E5B","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "net.yanue.V2rayU",
  "crashReporterKey" : "",
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "asi" : {"libsystem_c.dylib":["abort() called"]},
  "asiBacktraces" : ["0   CoreFoundation                      0x000000019af7d1a8 __exceptionPreprocess + 240\n1   libobjc.A.dylib                     0x000000019acc7e04 objc_exception_throw + 60\n2   Foundation                          0x000000019be63130 -[NSConcreteTask dealloc] + 0\n3   V2rayU                              0x0000000104a6ec38 V2rayU + 76856\n4   V2rayU                              0x0000000104a65e94 V2rayU + 40596\n5   V2rayU                              0x0000000104a668ac V2rayU + 43180\n6   CoreFoundation                      0x000000019aef0864 -[NSSet makeObjectsPerformSelector:] + 216\n7   AppKit                              0x000000019da3f51c -[NSIBObjectData nibInstantiateWithOwner:options:topLevelObjects:] + 1080\n8   AppKit                              0x000000019da33800 loadNib + 416\n9   AppKit                              0x000000019da32d30 +[NSBundle(NSNibLoading) _loadNibFile:nameTable:options:withZone:ownerBundle:] + 800\n10  AppKit                              0x000000019da32934 -[NSBundle(NSNibLoading) loadNibNamed:owner:topLevelObjects:] + 220\n11  AppKit                              0x000000019da32704 +[NSBundle(NSNibLoading) loadNibNamed:owner:] + 388\n12  AppKit                              0x000000019da244d0 NSApplicationMain + 576\n13  V2rayU                              0x0000000104a621e4 V2rayU + 25060\n14  dyld                                0x0000000104d5908c start + 520"],
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "lastExceptionBacktrace" : [{"imageOffset":1069460,"symbol":"__exceptionPreprocess","symbolLocation":220,"imageIndex":7},{"imageOffset":101892,"symbol":"objc_exception_throw","symbolLocation":60,"imageIndex":4},{"imageOffset":946480,"symbol":"-[NSConcreteTask dealloc]","symbolLocation":0,"imageIndex":5},{"imageOffset":76856,"imageIndex":6},{"imageOffset":40596,"imageIndex":6},{"imageOffset":43180,"imageIndex":6},{"imageOffset":493668,"symbol":"-[NSSet makeObjectsPerformSelector:]","symbolLocation":216,"imageIndex":7},{"imageOffset":124188,"symbol":"-[NSIBObjectData nibInstantiateWithOwner:options:topLevelObjects:]","symbolLocation":1080,"imageIndex":8},{"imageOffset":75776,"symbol":"loadNib","symbolLocation":416,"imageIndex":8},{"imageOffset":73008,"symbol":"+[NSBundle(NSNibLoading) _loadNibFile:nameTable:options:withZone:ownerBundle:]","symbolLocation":800,"imageIndex":8},{"imageOffset":71988,"symbol":"-[NSBundle(NSNibLoading) loadNibNamed:owner:topLevelObjects:]","symbolLocation":220,"imageIndex":8},{"imageOffset":71428,"symbol":"+[NSBundle(NSNibLoading) loadNibNamed:owner:]","symbolLocation":388,"imageIndex":8},{"imageOffset":13520,"symbol":"NSApplicationMain","symbolLocation":576,"imageIndex":8},{"imageOffset":25060,"imageIndex":6},{"imageOffset":20620,"symbol":"start","symbolLocation":520,"imageIndex":9}],
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":9103,"threadState":{"x":[{"value":0},{"value":0},{"value":0},{"value":0},{"value":6893265141},{"value":6093936832},{"value":110},{"value":1},{"value":10880993718283549260},{"value":10880993713917591500},{"value":512},{"value":11},{"value":11},{"value":6898836205},{"value":6893265179},{"value":9653195},{"value":328},{"value":8404661888},{"value":0},{"value":6},{"value":4376544640,"symbolLocation":0,"symbol":"_main_thread"},{"value":259},{"value":4376544864,"symbolLocation":224,"symbol":"_main_thread"},{"value":5526125600},{"value":5795521728},{"value":123649615159650},{"value":5794555888},{"value":5795572464},{"value":8386194488,"symbolLocation":0,"symbol":"OBJC_CLASS_$_NSTask"}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6893534944},"cpsr":{"value":1073745920},"fp":{"value":6093936688},"sp":{"value":6093936656},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6893317528,"matchesCrashFrame":1},"far":{"value":6160596472}},"queue":"com.apple.main-thread","frames":[{"imageOffset":40344,"symbol":"__pthread_kill","symbolLocation":8,"imageIndex":0},{"imageOffset":28384,"symbol":"pthread_kill","symbolLocation":288,"imageIndex":1},{"imageOffset":500544,"symbol":"abort","symbolLocation":168,"imageIndex":2},{"imageOffset":72456,"symbol":"abort_message","symbolLocation":132,"imageIndex":3},{"imageOffset":6480,"symbol":"demangling_terminate_handler()","symbolLocation":336,"imageIndex":3},{"imageOffset":135968,"symbol":"_objc_terminate()","symbolLocation":144,"imageIndex":4},{"imageOffset":69284,"symbol":"std::__terminate(void (*)())","symbolLocation":20,"imageIndex":3},{"imageOffset":80924,"symbol":"__cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*)","symbolLocation":36,"imageIndex":3},{"imageOffset":80840,"symbol":"__cxa_throw","symbolLocation":140,"imageIndex":3},{"imageOffset":102252,"symbol":"objc_exception_throw","symbolLocation":420,"imageIndex":4},{"imageOffset":946480,"symbol":"-[NSConcreteTask terminationStatus]","symbolLocation":204,"imageIndex":5},{"imageOffset":76856,"imageIndex":6},{"imageOffset":40596,"imageIndex":6},{"imageOffset":43180,"imageIndex":6},{"imageOffset":493668,"symbol":"-[NSSet makeObjectsPerformSelector:]","symbolLocation":216,"imageIndex":7},{"imageOffset":124188,"symbol":"-[NSIBObjectData nibInstantiateWithOwner:options:topLevelObjects:]","symbolLocation":1080,"imageIndex":8},{"imageOffset":75776,"symbol":"loadNib","symbolLocation":416,"imageIndex":8},{"imageOffset":73008,"symbol":"+[NSBundle(NSNibLoading) _loadNibFile:nameTable:options:withZone:ownerBundle:]","symbolLocation":800,"imageIndex":8},{"imageOffset":71988,"symbol":"-[NSBundle(NSNibLoading) loadNibNamed:owner:topLevelObjects:]","symbolLocation":220,"imageIndex":8},{"imageOffset":71428,"symbol":"+[NSBundle(NSNibLoading) loadNibNamed:owner:]","symbolLocation":388,"imageIndex":8},{"imageOffset":13520,"symbol":"NSApplicationMain","symbolLocation":576,"imageIndex":8},{"imageOffset":25060,"imageIndex":6},{"imageOffset":20620,"symbol":"start","symbolLocation":520,"imageIndex":9}]},{"id":9154,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":9155,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":9158,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6893277184,
    "size" : 229376,
    "uuid" : "67f22904-88ed-3847-bbf0-5c4c599fd79e",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6893506560,
    "size" : 53248,
    "uuid" : "f32ff902-ba43-30b0-ad43-a2a8a9ff69fe",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6892224512,
    "size" : 532480,
    "uuid" : "93fc2587-038e-31e1-b16b-369979e72cb1",
    "path" : "\/usr\/lib\/system\/libsystem_c.dylib",
    "name" : "libsystem_c.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6893178880,
    "size" : 98304,
    "uuid" : "a260a581-f4a9-3036-bb4f-16a9c6cc54d5",
    "path" : "\/usr\/lib\/libc++abi.dylib",
    "name" : "libc++abi.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6891958272,
    "size" : 253952,
    "uuid" : "3d936842-5903-31ad-b1ae-1de4f4b448a6",
    "path" : "\/usr\/lib\/libobjc.A.dylib",
    "name" : "libobjc.A.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6909575168,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.Foundation",
    "size" : 4136960,
    "uuid" : "59ff845a-05b2-3b64-ae06-6ef1d6aee83e",
    "path" : "\/System\/Library\/Frameworks\/Foundation.framework\/Versions\/C\/Foundation",
    "name" : "Foundation",
    "CFBundleVersion" : "1866"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4372938752,
    "CFBundleShortVersionString" : "3.3.0",
    "CFBundleIdentifier" : "net.yanue.V2rayU",
    "size" : 917504,
    "uuid" : "73ec5a51-3e6f-396f-94dd-b0eb68a027c0",
    "path" : "\/Applications\/V2rayU.app\/Contents\/MacOS\/V2rayU",
    "name" : "V2rayU",
    "CFBundleVersion" : "3.3.0"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6893830144,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5533696,
    "uuid" : "",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1866"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6939611136,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 15437824,
    "uuid" : "07bc3607-552a-3eb9-a941-4911c589dbc5",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2113.60.148"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4376051712,
    "size" : 393216,
    "uuid" : "75627683-a780-32ad-ae34-cf86dd23a26b",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "sharedCache" : {
  "base" : 6890209280,
  "size" : 3144695808,
  "uuid" : "ffede77c-d90b-366b-96f2-665c2f50ee59"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)\nWritable regions: Total=498.5M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=498.5M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nColorSync                          528K       23 \nCoreGraphics                        16K        1 \nCoreServices                       208K        1 \nDispatch continuations            64.0M        1 \nFoundation                          16K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                            64.3M       26 \nMALLOC guard page                  192K        9 \nMALLOC_MEDIUM (reserved)         360.0M        3         reserved VM address space (unallocated)\nSTACK GUARD                       56.1M        4 \nStack                             9808K        4 \nVM_ALLOCATE                         48K        3 \n__AUTH                            2244K      228 \n__AUTH_CONST                      17.5M      407 \n__CTF                               756        1 \n__DATA                            11.2M      404 \n__DATA_CONST                      15.3M      419 \n__DATA_DIRTY                      1440K      162 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       579.7M       11 \n__OBJC_CONST                      2589K      198 \n__OBJC_RO                         83.0M        1 \n__OBJC_RW                         3168K        1 \n__TEXT                           426.4M      436 \n__UNICODE                          592K        1 \ndyld private memory               1024K        1 \nmapped file                      135.4M       16 \nshared memory                      848K       13 \n===========                     =======  ======= \nTOTAL                              1.8G     2378 \nTOTAL, minus reserved VM space     1.4G     2378 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "6112dda2fc54bc3389840642",
      "factorPackIds" : {
        "SIRI_DICTATION_ASSETS" : "631730a28520965d1cba0681"
      },
      "deploymentId" : 240000145
    },
    {
      "rolloutId" : "607844aa04477260f58a8077",
      "factorPackIds" : {
        "SIRI_MORPHUN_ASSETS" : "6103050cbfe6dc472e1c982a"
      },
      "deploymentId" : 240000066
    }
  ],
  "experiments" : [

  ]
}
}

Model: Mac14,7, BootROM 7459.141.1, proc 8:4:4 processors, 16 GB, SMC 
Graphics: Apple M2, Apple M2, Built-In
Display: Color LCD, 2560 x 1600 Retina, Main, MirrorOff, Online
Memory Module: LPDDR5
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.

**Comment by xtrabet** [comment]
+1 我也碰到了这个情况。。。

**Comment by kentchou** [comment]
我一直也是这个提示

**Comment by WYYlost** [comment]
我也有这个提示，一直更新不了最新版

**Comment by yanue** [comment]
手动更新
